import type { Metadata } from "next";
import "./globals.css";
import "lenis/dist/lenis.css";
import NextTopLoader from "nextjs-toploader";
import AuthSessionProvider from "@/components/provider/AuthSessionProvider";
import SmoothScrollProvider from "@/components/provider/SmoothScrollprovider";
import { Toaster } from "@/components/ui/toast";
import { Toaster as SonnerToaster } from "sonner";

export const metadata: Metadata = {
  title: "A7 PROPERTY SOLUTIONS",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-sans">
        <NextTopLoader color="#BB7B1D" height={3} showSpinner={false} />
        <AuthSessionProvider>
          <SmoothScrollProvider>{children}</SmoothScrollProvider>
        </AuthSessionProvider>
        <Toaster position="top-right" />
        <SonnerToaster richColors position="top-right" />
      </body>
    </html>
  );
}
